/* Path Beaters '26 options board: route data.
   miles/gain/high are rounded from AllTrails or the linked guide; drive is hours from SLC airport, highway estimate.
   epic / logistics / novelty are 1–10 gut ratings. wu is the Weather Underground town page (10-day forecast). */
const ROUTES = [
  { id: "spanish", region: "mt", name: "Spanish Peaks Loop", where: "Lee Metcalf Wilderness, Madison Range, MT", th: "Spanish Creek TH (6,100 ft)",
    miles: 20, gain: 5500, high: 9435, nights: "3 on trail", drive: 6.5, driveNote: "via Pocatello; 4.5–5 hr from Dad's", fly: "BZN (1 hr) Monday",
    permits: "None", bears: "Grizzly: spray + canisters", wu: "mt/gallatin-gateway",
    epic: 7, logistics: 7, novelty: 10, done: "New range for us",
    why: ["Already planned, mapped, and waypointed; the rigs know the way.", "Big lake camps with room for eight, no permits, no shuttle.", "The Bozeman fly-out Monday is the cleanest exit of the bunch."],
    whynot: ["The wettest forecast on the board: storms likely Thursday night and all Friday, still showery Saturday.", "Longest drive from SLC.", "The one summit that fits (Blaze) is an off-trail scramble; no signature objective on trail."],
    shape: "Thu 6 pm rigs at TH or 3 mi in · Fri Spanish Lakes · Sat over the divide to Jerome Rock Lakes · Sun low camp on Falls Creek · Mon out by 10, BZN by 11:30.",
    links: [["Trip site", "../"], ["AllTrails area", "https://www.alltrails.com/parks/us/montana/lee-metcalf-wilderness"]] },

  { id: "cirque", region: "wy", name: "Cirque of the Towers → Fremont Trail Loop", where: "Bridger Wilderness, Wind River Range, WY", th: "Big Sandy TH (9,100 ft)",
    miles: 24, gain: 3900, high: 11400, nights: "3 on trail", drive: 5, driveNote: "last 40 mi is washboard dirt", fly: "SLC Mon night or Tue; JAC 2.5 hr",
    permits: "None (self-register)", bears: "Black bear country, grizzly possible; spray + storage", wu: "wy/boulder",
    epic: 10, logistics: 8, novelty: 6, done: "Winds in 2022 and 2024",
    why: ["The single most photographed backcountry skyline in the Lower 48, and Lonesome Lake camp sits right under it.", "A real loop with two passes; every day has a new basin.", "Texas Pass is a mild scramble that feels like an accomplishment without being dangerous when dry."],
    whynot: ["Thursday is stormy at Big Sandy; Friday is the iffy one at the high point, then it clears.", "Big Sandy is famous for a reason: expect neighbors at Lonesome Lake on a weekend.", "We've been to the Winds twice already; the novelty is in the Cirque itself, not the range."],
    shape: "Thu 6 pm camp at Big Sandy TH (big, free, vault toilet) · Fri Big Sandy Lake → Jackass Pass → Lonesome Lake (9 mi) · Sat Texas Pass → Shadow Lake / Washakie Creek (7 mi) · Sun Fremont Trail → Dads or Marms Lake (6 mi) · Mon 6 mi out, drive home.",
    links: [["AllTrails", "https://www.alltrails.com/trail/us/wyoming/cirque-of-the-towers-to-fremont-trail-loop"], ["Bearfoot Theory guide", "https://bearfoottheory.com/cirque-of-the-towers-backpacking-wyoming/"], ["Girl on a Hike report", "https://girlonahike.com/hiking-the-cirque-of-the-towers-to-fremont-trail-loop.html"]] },

  { id: "lizardhead", region: "wy", name: "Lizard Head Plateau → Cirque (Dickinson Park to Big Sandy)", where: "Popo Agie + Bridger Wilderness, Wind River Range, WY", th: "Bears Ears TH, Dickinson Park (9,300 ft) → Big Sandy TH",
    miles: 27, gain: 5000, high: 11864, nights: "3 on trail", drive: 5.5, driveNote: "via Lander; 16 mi of rough dirt through the reservation to Dickinson Park", fly: "SLC Mon night or Tue",
    permits: "None; check Wind River Reservation road access", bears: "Grizzly possible; spray + storage", wu: "wy/lander",
    epic: 10, logistics: 4, novelty: 8, done: "Never from the east side",
    why: ["Five and a half miles above treeline on a tundra plateau at 11,500 ft with the whole southern Winds in view; the Cirque is the finale, not the whole show.", "The east side is empty compared with Big Sandy.", "Ends at Big Sandy with the classic Cirque camps and an easy exit."],
    whynot: ["Point-to-point: the rig shuttle between Dickinson Park and Big Sandy is 3.5 hours each way.", "The plateau has zero cover from lightning; Thursday and Friday storms make the timing tight.", "Longest and highest walking of the Wyoming options; Friday from Dickinson Park is 11 mi."],
    shape: "Thu 6 pm camp at Dickinson Park (drop one rig at Big Sandy on the way, or hire the Lander shuttle) · Fri Bears Ears Trail → Valentine Lake (10 mi) · Sat over the Lizard Head Plateau → Lonesome Lake (9 mi, weather-dependent) · Sun Jackass Pass → Big Sandy Lake or Deep Lake (5 mi) · Mon 6 mi out.",
    links: [["Hiking Walking guide", "https://www.hikingwalking.org/index.php/destinations/wy/wy_ww/big_sandy/wp_lh_ct/valentine_ct"], ["CMC 5-day loop version", "https://www.cmc.org/education-adventure/trips/routes-places/bpx-routes-places/bpx-5-day-washakie-pass-lizard-head-and-cirque-of-towers-loop"], ["Big Outside traverse", "https://thebigoutside.com/a-walk-in-the-winds-hiking-a-one-day-27-mile-traverse-of-wyomings-wind-river-range/"]] },

  { id: "titcomb", region: "wy", name: "Titcomb Basin via Pole Creek + Indian Basin", where: "Bridger Wilderness, Wind River Range, WY", th: "Elkhart Park TH (9,300 ft)",
    miles: 32, gain: 4500, high: 10800, nights: "3 on trail", drive: 4.25, driveNote: "paved to the trailhead, Pinedale is 15 mi away", fly: "SLC Mon night; JAC 1.5 hr",
    permits: "None", bears: "Grizzly range; spray + storage required", wu: "wy/pinedale",
    epic: 9, logistics: 8, novelty: 6, done: "Winds in 2022 and 2024",
    why: ["Titcomb is the Winds' cathedral: two miles of lakes under Fremont, Helen, and Sacagawea.", "Best drive on the board for a Wyoming trip: paved to the car.", "Indian Basin and Island Lake give a day-hike morning like our Sunday plan."],
    whynot: ["The high forecast is the coldest and snowiest here: snow showers likely Friday, highs in the upper 30s at 12,000 ft.", "Out-and-back, not a loop, and 12 miles in on day one is a big Friday after a rig night.", "Most exposed to weather of anything we're considering."],
    shape: "Thu 6 pm camp at Elkhart Park (campground at the TH) · Fri 12 mi to Island Lake · Sat day-pack Titcomb + Indian Basin, camp Island Lake again · Sun 8 mi back to Seneca / Hobbs Lake · Mon 4 mi out.",
    links: [["AllTrails", "https://www.alltrails.com/trail/us/wyoming/titcomb-basin-via-pole-creek-trail-crooks-lakes-loop"], ["Hiking Walking guide", "https://www.hikingwalking.com/destinations/wy/wy_ww/elkhart_park/bp_islandlake/titcomb_basin"]] },

  { id: "teton", region: "wy", name: "Teton Crest Trail (Death Canyon → Paintbrush)", where: "Grand Teton National Park, WY", th: "Death Canyon TH → String Lake TH (shuttle)",
    miles: 34, gain: 8000, high: 10700, nights: "3 on trail", drive: 5, driveNote: "to Moose; two rigs make the shuttle free", fly: "JAC 30 min; SLC 5 hr",
    permits: "Required, camping zones; walk-in permits the day before at Jenny Lake", bears: "Grizzly: canisters required by the park", wu: "wy/moose",
    epic: 10, logistics: 4, novelty: 9, done: "New for the group",
    why: ["Hurricane Pass puts the Grand in your face; nothing else on this list touches it for drama.", "Two rigs solve the shuttle; JAC is the closest airport of any option.", "Late September is the classic window: crowds gone, larches turning, permits easier."],
    whynot: ["Permits are the whole game: a third of zones are walk-in, first-come, the morning before. Eight people needs a group zone.", "8,000 ft of gain over 34 mi is a bigger physical ask than the Spanish Peaks.", "Paintbrush Divide can hold early snow and the park may require an ice axe; check the day before."],
    shape: "Thu 6 pm camp at Gros Ventre CG · Fri Death Canyon → the Shelf (9 mi) · Sat Alaska Basin → Hurricane Pass → S Fork Cascade (10 mi) · Sun N Fork Cascade → Lake Solitude → Paintbrush Divide → Holly Lake (8 mi) · Mon 7 mi out to String Lake, home.",
    links: [["AllTrails (full TCT)", "https://www.alltrails.com/trail/us/wyoming/teton-crest-trail--3"], ["NPS backcountry permits", "https://www.nps.gov/grte/planyourvisit/backcountry-camping.htm"]] },

  { id: "alice", region: "id", name: "Alice–Toxaway Loop (Tin Cup Hiker)", where: "Sawtooth Wilderness, ID", th: "Tin Cup TH, Pettit Lake (7,000 ft)",
    miles: 19, gain: 3000, high: 9400, nights: "2–3 on trail", drive: 5, driveNote: "via Twin Falls and Ketchum, paved to Pettit", fly: "SLC Mon night; BOI 3 hr",
    permits: "Free self-issue at TH", bears: "Black bear only; hang or canister", wu: "id/stanley",
    epic: 8, logistics: 9, novelty: 3, done: "Sawtooths 2017, 2020, 2021, 2023",
    why: ["Dries out fastest of anything north of Utah: sunny and near-zero precip by Saturday.", "The prettiest single lake-to-pass-to-lake day in Idaho, and we know the drive.", "Short enough to add the Imogene Lake extension (25 mi) if legs are fresh."],
    whynot: ["We've been to the Sawtooths four times; odds are somebody has done this exact loop.", "Only 19 miles and 3,000 ft: the lightest mountain challenge on the board.", "Pettit Lake is the busiest trailhead in the range on a nice September weekend."],
    shape: "Thu 6 pm camp at Pettit Lake CG · Fri 6 mi to Alice Lake · Sat over Snowyside Pass to Toxaway Lake (6 mi) · Sun Imogene Lake side trip, camp Farley/Edith · Mon 6 mi out, drive home.",
    links: [["AllTrails", "https://www.alltrails.com/trail/us/idaho/tin-cup-hiker"], ["Imogene extension", "https://www.alltrails.com/trail/us/idaho/imogene-lake-to-toxaway-lake-to-alice-lake-loop"]] },

  { id: "baron", region: "id", name: "Redfish → Baron Lakes → Grandjean traverse", where: "Sawtooth Wilderness, ID", th: "Redfish Lake inlet (boat shuttle) → Grandjean TH",
    miles: 24, gain: 5400, high: 9200, nights: "3 on trail", drive: 5.25, driveNote: "to Redfish; the Grandjean rig is 1 hr further around", fly: "SLC Mon night; BOI 2.5 hr",
    permits: "Free self-issue", bears: "Black bear only", wu: "id/stanley",
    epic: 9, logistics: 6, novelty: 4, done: "Sawtooths 4 times; probably not this line",
    why: ["Alpine Lake, Baron Divide, and the Baron Lakes under Monte Verita are the Sawtooths' most dramatic corner.", "Same clearing forecast as Alice–Toxaway.", "The Redfish boat shuttle knocks 5 miles off day one and is a fun start."],
    whynot: ["Point-to-point: one rig has to be at Grandjean, an hour's drive around.", "5,400 ft of gain in 24 mi, most of it Friday and Saturday.", "It's the Sawtooths again."],
    shape: "Thu 6 pm camp at Redfish (Glacier View / Point CG) · Fri boat to the inlet, up Redfish Creek to Alpine Lake (6 mi) · Sat Baron Divide → Baron Lakes (5 mi), afternoon at Upper Baron · Sun Baron Creek → Grandjean side, camp low (9 mi) · Mon 4 mi out to Grandjean, shuttle back.",
    links: [["AllTrails (Grandjean to Redfish)", "https://www.alltrails.com/trail/us/idaho/grandjean-to-redfish-via-baron-lake"], ["Bearfoot Theory guide", "https://bearfoottheory.com/baron-lakes-idaho-backpacking-guide/"]] },

  { id: "whiteclouds", region: "id", name: "Castle Peak Circuit (Chamberlain → Boulder Chain Lakes)", where: "Cecil D. Andrus–White Clouds Wilderness, ID", th: "Fourth of July TH (9,900 ft)",
    miles: 30, gain: 6000, high: 10500, nights: "3 on trail", drive: 5.75, driveNote: "Ketchum, over Galena, then 10 mi of decent dirt", fly: "SLC Mon night; BOI 3.5 hr",
    permits: "Free self-issue; group limit 12", bears: "Black bear only", wu: "id/stanley",
    epic: 9, logistics: 7, novelty: 8, done: "Never; neighbors of the Sawtooths",
    why: ["Same clear-by-Saturday forecast as the Sawtooths with a fraction of the people.", "A true loop around one giant mountain; Chamberlain Basin under Castle Peak's north face is the camp of the trip.", "Highest trailhead on the board, so the climbs are short and the camps are high."],
    whynot: ["Longest Idaho drive and the last stretch is dirt.", "Castle Divide (10,300) and Windy Devil pass are rocky; poles and steady feet.", "Less documented than the Sawtooths: paper map and GPX matter more here."],
    shape: "Thu 6 pm camp at Fourth of July TH (primitive, no water) · Fri Ants Basin → Chamberlain Basin (8 mi) · Sat Castle Divide → Baker Lake / Boulder Chain Lakes (8 mi) · Sun up the chain → Windy Devil → Four Lakes / Born Lakes (7 mi) · Mon 6 mi out over Fourth of July Lake.",
    links: [["Mountaineers route", "https://www.mountaineers.org/activities/routes-places/white-clouds-wilderness-loop"], ["AllTrails (harder off-trail variant)", "https://www.alltrails.com/trail/us/idaho/white-cloud-peaks-loop"], ["Fourth of July TH", "https://www.alltrails.com/trail/us/idaho/fourth-of-july-lake-trail"]] },

  { id: "hyndman", region: "id", name: "Hyndman Peak + Pioneer Cabin (Pioneer Mountains)", where: "Pioneer Mountains, Sawtooth NF, ID", th: "Hyndman Creek TH (6,900 ft)",
    miles: 20, gain: 6000, high: 12009, nights: "2–3 on trail", drive: 4.75, driveNote: "via Ketchum and Hailey; 6 mi of gravel up East Fork", fly: "SLC Mon night; BOI 2.5 hr",
    permits: "None", bears: "Black bear only", wu: "id/ketchum",
    epic: 8, logistics: 8, novelty: 9, done: "Never; the range next to the Sawtooths nobody talks about",
    why: ["A 12,009-ft summit with no technical ground, from a high base camp under the Devil's Bedstead.", "Pioneer Cabin (1937 ski hut) and its 'The higher you get, the higher you get' sign is the crew photo.", "Drying forecast, short drive for Idaho, and empty compared with Stanley."],
    whynot: ["It's a base-camp-and-summit trip, not a lake-to-lake loop; less variety per day.", "Summit day is 5,000 ft of gain and back; Sunday needs to be clear.", "Camps are in a valley, not on a lake."],
    shape: "Thu 6 pm camp at the trailhead (dispersed) · Fri 6 mi up Hyndman Creek to the upper basin camp (9,400 ft) · Sat Hyndman Peak, 6 mi RT and 2,600 ft, afternoon in camp · Sun over to Pioneer Cabin via the Johnstone Creek col, camp near the cabin (6 mi) · Mon 4 mi out the Corral Creek side, rigs shuttled 20 min.",
    links: [["AllTrails Hyndman Peak", "https://www.alltrails.com/trail/us/idaho/hyndman-peak"], ["Pioneer Cabin via Hyndman", "https://www.alltrails.com/trail/us/idaho/pioneer-cabin-via-hyndman-trailhead"], ["Idaho Summits route", "https://www.idahosummits.com/Hyndman/hyndman.htm"]] },

  { id: "kings", region: "utm", name: "Kings Peak via Henrys Fork", where: "High Uintas Wilderness, UT", th: "Henrys Fork TH (9,400 ft)",
    miles: 26, gain: 4200, high: 13528, nights: "2–3 on trail", drive: 2.75, driveNote: "shortest of the big ones; 20 mi of good gravel at the end", fly: "SLC Mon evening, easy",
    permits: "None", bears: "Black bear; hang", wu: "wy/mountain-view",
    epic: 7, logistics: 10, novelty: 7, done: "Not as a group",
    why: ["Two-hour-forty-five drive means a real Thursday evening walk-in and a leisurely Monday.", "Summit day on the state high point, 13,528 ft, no technical ground.", "Dries out Saturday; a Sunday summit looks clean if the trend holds."],
    whynot: ["Thursday and Friday are the worst-looking forecast on the board: 83% storms Thursday, likely Friday, snow showers possible Saturday above 12,000 ft.", "Big open windy basins; camps are exposed and the Uintas lack the granite drama of the Winds.", "Henrys Fork is the busiest Uinta trailhead."],
    shape: "Thu 6 pm hike 3 mi to Alligator Lake · Fri to Dollar Lake (6 mi) · Sat Gunsight → Anderson Pass → Kings Peak → back (12 mi RT) · Sun down to Henrys Fork Lake or all the way out · Mon short walk out, home by lunch.",
    links: [["AllTrails", "https://www.alltrails.com/trail/us/utah/kings-peak-utah-highpoint-trail"], ["Highpoint guide", "https://highpoint.guide/ut/"]] },

  { id: "redcastle", region: "utm", name: "Red Castle Lakes (+ Smiths Fork Pass)", where: "High Uintas Wilderness, UT", th: "China Meadows TH (9,400 ft)",
    miles: 24, gain: 3000, high: 11800, nights: "2–3 on trail", drive: 2.75, driveNote: "via Mountain View, WY; 20 mi of gravel", fly: "SLC Mon evening, easy",
    permits: "None", bears: "Black bear; hang", wu: "wy/mountain-view",
    epic: 8, logistics: 9, novelty: 8, done: "Never as a group",
    why: ["Red Castle is the most photogenic mountain in Utah and the lake under it is a 10 out of 10 camp.", "Short drive, gentle miles, and Smiths Fork Pass (11,800) as the challenge day with Kings Peak in view.", "Can link to Kings Peak for a 40-mi loop if the group wants more."],
    whynot: ["Same Thursday/Friday storm forecast as Kings.", "Out-and-back unless we do the long loop.", "Popular with Wyoming horse packers; expect stock at the lower lake."],
    shape: "Thu 6 pm hike 2 mi to the wilderness boundary meadows · Fri 9 mi to Lower Red Castle Lake, camp · Sat day pack: Upper Red Castle, Smiths Fork Pass, maybe the Wilson Peak ridge · Sun 7 mi back to Broadbent Meadow · Mon 4 mi out, home for dinner.",
    links: [["AllTrails (loop w/ Kings Peak)", "https://www.alltrails.com/trail/us/utah/red-castle-lake-and-king-s-peak-loop-from-china-meadows"]] },

  { id: "naturalist", region: "utm", name: "Naturalist + Four Lakes + Grandaddy Basins (Highline loop)", where: "High Uintas Wilderness, UT", th: "Highline TH, Hayden Pass (10,300 ft)",
    miles: 30, gain: 4500, high: 11300, nights: "3 on trail", drive: 2.25, driveNote: "Mirror Lake Highway, paved to the trailhead", fly: "SLC Mon afternoon",
    permits: "None; Mirror Lake fee area for parking", bears: "Black bear; hang", wu: "ut/kamas",
    epic: 6, logistics: 10, novelty: 6, done: "Some of us in pieces",
    why: ["Closest trailhead on the board: dinner at the trailhead Thursday and still time to walk in.", "Three basins, dozens of lakes, Rocky Sea Pass; a lot of country for the miles.", "Bailout options everywhere if the weather turns."],
    whynot: ["The Uintas are rolling and forested; less 'epic' per mile than anything in Wyoming or Idaho.", "Thursday and Friday look wet here too.", "Weekend crowds from SLC on the near lakes."],
    shape: "Thu 6 pm hike 3 mi to Scudder Lake · Fri Naturalist Basin, Blue Lake, camp Jordan Lake (7 mi) · Sat Rocky Sea Pass → Four Lakes Basin (8 mi) · Sun Grandaddy Basin → Pinto Lake (8 mi) · Mon 5 mi out via the Highline.",
    links: [["AllTrails loop", "https://www.alltrails.com/trail/us/utah/highline-trailhead-loop-naturalist-four-lakes-and-grandaddy-basins"], ["Naturalist Basin guide", "https://girlonahike.com/backpacking-to-naturalist-basin-uintas.html"]] },

  { id: "tushar", region: "utm", name: "Tushar Skyline: Delano, Belknap, Baldy", where: "Tushar Mountains, Fishlake NF, UT", th: "Big John Flat TH (10,300 ft)",
    miles: 23, gain: 5000, high: 12169, nights: "2–3 on trail", drive: 3.75, driveNote: "I-15 to Beaver, then 20 mi up UT-153 and forest road", fly: "SLC Mon evening, easy",
    permits: "None", bears: "Black bear; hang", wu: "ut/beaver",
    epic: 7, logistics: 9, novelty: 9, done: "Never; Utah's forgotten third range",
    why: ["Three 12,000-ft summits in a weekend from a tundra trail with mountain goats and no crowds.", "Drier than the Uintas Thursday and Friday.", "High trailhead, short drive, no permits."],
    whynot: ["Water is scarce on the Skyline; carry from the few springs.", "Not a lake-camp trip.", "Aspen gold is the show, and it peaks about a week later than our dates."],
    shape: "Thu 6 pm camp at Big John Flat · Fri Skyline Trail to Mud Lake / Blue Lake, tag Delano on the way (8 mi) · Sat Mount Belknap and Baldy from camp (8 mi RT) · Sun down to Bullion Pasture, camp (5 mi) · Mon 3 mi out, home by lunch.",
    links: [["Skyline Trail (Outdoor Project)", "https://www.outdoorproject.com/united-states/utah/tushar-skyline-trail-hike"], ["Delano Peak AllTrails", "https://www.alltrails.com/trail/us/utah/delano-peak"], ["Visit Utah three summits", "https://www.visitutah.com/articles/three-summits-tushar-mountains"]] },

  { id: "grandgulch", region: "ut", name: "Grand Gulch: Kane Gulch → Bullet Canyon", where: "Cedar Mesa, Bears Ears NM, UT", th: "Kane Gulch Ranger Station (6,500 ft)",
    miles: 23, gain: 1800, high: 6600, nights: "3 on trail", drive: 5.5, driveNote: "via Moab, Blanding, UT-95, UT-261; paved to Kane Gulch", fly: "SLC Mon night or Tue",
    permits: "Required: BLM Cedar Mesa overnight permit, group cap 12, recreation.gov", bears: "None to speak of; mice and ravens", wu: "ut/blanding",
    epic: 8, logistics: 6, novelty: 10, done: "Never; a completely different kind of trip",
    why: ["Warm and drying: mid-70s days, low 50s nights, nearly clear from Saturday.", "Ruins, granaries, and panels around every bend; it's a walk through 900-year-old neighborhoods.", "Low mileage and gain leave energy for side canyons."],
    whynot: ["Permits are limited and must be reserved; a group of eight needs to land one now.", "Water is pools, sometimes brown, sometimes missing in September; carry capacity for a dry day.", "Not 'mountain epic': no passes, no summits, and the wash-bottom miles are sandy and slow."],
    shape: "Thu 6 pm camp at Kane Gulch (primitive) or Natural Bridges CG · Fri Kane Gulch → Junction Ruin → Todie area (7 mi) · Sat past Split Level and Sheiks Canyon to the Bullet junction (8 mi) · Sun up Bullet to Jailhouse and Perfect Kiva, camp near the rim (6 mi) · Mon 2 mi out; bike or second rig back to Kane Gulch.",
    links: [["AllTrails", "https://www.alltrails.com/trail/us/utah/bullet-canyon-trail-to-grand-gulch-and-kane-gulch"], ["BLM Cedar Mesa permits", "https://www.blm.gov/visit/cedar-mesa"]] },

  { id: "deathhollow", region: "ut", name: "Death Hollow Loop (Boulder Mail Trail → Escalante River)", where: "Grand Staircase–Escalante NM, UT", th: "Boulder Mail Trail TH (6,600 ft)",
    miles: 22, gain: 3000, high: 6800, nights: "2–3 on trail", drive: 4.75, driveNote: "via US-89 and Highway 12, one of the great drives", fly: "SLC Mon night, easy",
    permits: "Free self-issue at the TH; wag bags required in the canyons", bears: "None", wu: "ut/escalante",
    epic: 9, logistics: 8, novelty: 10, done: "Never; the wild card",
    why: ["Best forecast on the board: mid-70s, 20% precip or lower after Thursday, warm nights.", "Death Hollow is a legitimately hard canyon: wading, scrambling, route-finding, and the best swimming holes in Utah.", "Highway 12 in, free permits, and a short drive for the far-flung options."],
    whynot: ["Thursday storms in slot country mean flash-flood awareness; we don't drop into Death Hollow until Friday.", "Poison ivy is real and constant; long pants and no bare-armed bushwhacking.", "Only 22 mi; the challenge is the terrain, not the distance. Some of the crew may want a summit."],
    shape: "Thu 6 pm camp at the Boulder Mail Trail TH or Deer Creek CG · Fri Boulder Mail Trail across the slickrock, drop into Death Hollow (8 mi) · Sat down Death Hollow to the Escalante (7 mi, all wading) · Sun up the Escalante River toward town, camp in the corridor · Mon short walk out, 15-min shuttle between trailheads.",
    links: [["AllTrails", "https://www.alltrails.com/trail/us/utah/death-hollow-boulder-mail-trail-loop"], ["The Big Outside report", "https://thebigoutside.com/backpacking-utahs-mind-blowing-death-hollow-loop/"], ["Visit Utah guide", "https://www.visitutah.com/places-to-go/parks-outdoors/grand-staircase-escalante/hiking/boulder-mail-death-hollow"]] },

  { id: "coyote", region: "ut", name: "Coyote Gulch: Hurricane Wash → Crack-in-the-Wall", where: "Glen Canyon NRA / Escalante, UT", th: "Hurricane Wash TH, Hole-in-the-Rock Rd (4,600 ft)",
    miles: 20, gain: 1500, high: 4900, nights: "2–3 on trail", drive: 5, driveNote: "Highway 12 then 35 mi of Hole-in-the-Rock washboard", fly: "SLC Mon night",
    permits: "Free self-issue at the TH", bears: "None", wu: "ut/escalante",
    epic: 8, logistics: 8, novelty: 9, done: "Never as a group",
    why: ["Jacob Hamblin Arch, Coyote Natural Bridge, and a creek you walk in under 400-ft walls: the desert postcard.", "Warm, dry, and easy walking; more time for exploring and less for suffering.", "Crack-in-the-Wall and the pack-hauling rope is a real bit of fun."],
    whynot: ["Popular: the arch camps fill on a September weekend.", "Easiest trip on the board; the challenge factor is low.", "Hole-in-the-Rock Road after Thursday rain can be a mess for the Sprinter."],
    shape: "Thu 6 pm camp at the trailhead (dispersed) · Fri Hurricane Wash into Coyote Gulch, camp near Jacob Hamblin Arch (8 mi) · Sat down-canyon past the bridge to the Escalante, camp lower gulch (6 mi) · Sun out Crack-in-the-Wall to the Fortymile Ridge TH (3 mi), shuttle, or stay a night at Dance Hall Rock · Mon drive home.",
    links: [["AllTrails loop", "https://www.alltrails.com/trail/us/utah/coyote-gulch-loop"], ["Bearfoot Theory guide", "https://bearfoottheory.com/coyote-gulch-backpacking-guide/"]] },

  { id: "buckskin", region: "ut", name: "Buckskin Gulch: Wire Pass → White House", where: "Paria Canyon–Vermilion Cliffs Wilderness, UT/AZ", th: "Wire Pass TH (4,900 ft) → White House TH",
    miles: 21, gain: 500, high: 4900, nights: "1–2 on trail", drive: 5.75, driveNote: "US-89 past Kanab, 8 mi of House Rock Valley Rd dirt", fly: "SLC Mon night",
    permits: "Required: BLM, 20 people/night, reserve on recreation.gov; group max 10", bears: "None", wu: "ut/kanab",
    epic: 9, logistics: 4, novelty: 10, done: "Never",
    why: ["The longest slot canyon in the world: 13 miles of walls 400 ft high and 10 ft apart.", "Camp at the Buckskin–Paria confluence under 500-ft cliffs.", "Warm, and drying fast after Thursday."],
    whynot: ["Flash floods kill people here, and Thursday has storms in the forecast; we would not enter until the sky is clear.", "Overnight permits are capped and usually gone; check availability today.", "Too short for four days; pair with the Wave lottery or a Coyote Gulch day."],
    shape: "Thu 6 pm camp at Stateline CG near Wire Pass · Fri wait for a clear sky, Wire Pass → Buckskin → confluence camp (13 mi, wading) · Sat Paria narrows up to White House (7 mi), shuttle back, camp at White House · Sun Wave / Coyote Buttes lottery or Cottonwood Canyon Road side trip · Mon home.",
    links: [["AllTrails", "https://www.alltrails.com/trail/us/utah/wire-pass-trail-to-white-house-trailhead"], ["BLM permits", "https://www.blm.gov/programs/recreation/permits-and-passes/lotteries-and-permit-systems/arizona/paria-canyon"], ["Treeline Review guide", "https://www.treelinereview.com/where-to-go/buckskin-gulch-paria-canyon"]] },

  { id: "paria", region: "ut", name: "Paria Canyon: White House → Lees Ferry", where: "Paria Canyon–Vermilion Cliffs Wilderness, UT/AZ", th: "White House TH (4,300 ft) → Lees Ferry, AZ",
    miles: 38, gain: 400, high: 4300, nights: "3 on trail", drive: 5.5, driveNote: "US-89 past Kanab; Lees Ferry rig shuttle is 2 hr around", fly: "SLC Tue; PHX / LAS closer",
    permits: "Required: BLM, 20 people/day across all trailheads, 4 months ahead", bears: "None", wu: "ut/kanab",
    epic: 9, logistics: 3, novelty: 10, done: "Never",
    why: ["Four days in a canyon that gets deeper and wilder every mile: narrows, then springs, then hanging gardens, then the Colorado.", "Warm, and the Thursday storms clear before we'd be deep.", "A genuine expedition-feel trip."],
    whynot: ["Permits for eight people this week are nearly impossible.", "Flash flood exposure in the narrows for the first 8 miles.", "Long shuttle, and Lees Ferry is a long way from any Monday flight."],
    shape: "Thu 6 pm camp at White House · Fri narrows to the confluence and beyond (10 mi) · Sat Big Spring to Wrather Arch (10 mi) · Sun down to Bush Head Canyon (10 mi) · Mon 8 mi to Lees Ferry, 2-hr shuttle, fly Tuesday.",
    links: [["AllTrails", "https://www.alltrails.com/trail/us/utah/white-house-trail-to-lees-ferry"], ["Bearfoot Theory guide", "https://bearfoottheory.com/paria-canyon-backpacking-guide/"], ["Permit availability", "https://outdoorstatus.com/trips/us/utah/paria-canyon-vermilion-cliffs-wilderness/paria-canyon-white-house-to-lees-ferry/"]] },

  { id: "zion", region: "ut", name: "Zion Traverse: Lee Pass → the Grotto", where: "Zion National Park, UT", th: "Lee Pass TH, Kolob Canyons (6,100 ft) → Zion Canyon",
    miles: 37, gain: 6000, high: 7900, nights: "3 on trail", drive: 4.25, driveNote: "I-15 straight to Kolob; the Grotto rig via Springdale", fly: "SLC Mon night or LAS",
    permits: "Required: NPS backcountry sites, reserve or walk-in; group cap 12", bears: "None", wu: "ut/springdale",
    epic: 9, logistics: 5, novelty: 9, done: "Day hikes only",
    why: ["Kolob Arch, Hop Valley, Wildcat, the West Rim, and a finish above Angels Landing: Zion without the shuttle crowds.", "Warm days, cool nights, and a drying forecast.", "Pavement to both trailheads."],
    whynot: ["Permits: the West Rim sites for a Saturday night in late September go fast.", "Water is springs only for the middle two days; La Verkin Creek is the last reliable water until the rim.", "Two rigs a long way apart, or the Springdale shuttle companies."],
    shape: "Thu 6 pm camp at Lava Point CG (6 sites, or Kolob Terrace dispersed) with a rig staged in Springdale · Fri Lee Pass → La Verkin Creek → Hop Valley (13 mi) · Sat Hop Valley → Wildcat Canyon → Lava Point (9 mi) · Sun West Rim Trail to a rim site (8 mi) · Mon 7 mi down to the Grotto, lunch in Springdale, home.",
    links: [["CleverHiker guide", "https://www.cleverhiker.com/backpacking/zion-traverse-backpacking-guide/"], ["Joe's Guide (Trans-Zion)", "https://www.citrusmilo.com/zionguide/transziontrek.php"], ["NPS wilderness permits", "https://www.nps.gov/zion/planyourvisit/backpacking.htm"]] },

  { id: "needles", region: "ut", name: "Big Needles Loop (Chesler Park, Druid Arch, Lost Canyon)", where: "Needles District, Canyonlands NP, UT", th: "Elephant Hill TH (5,300 ft)",
    miles: 23, gain: 2500, high: 6000, nights: "3 on trail", drive: 5.25, driveNote: "via Moab and Monticello, paved to Elephant Hill", fly: "SLC Mon night",
    permits: "Required: NPS backcountry sites (max 7 per site), recreation.gov", bears: "None", wu: "ut/monticello",
    epic: 8, logistics: 5, novelty: 9, done: "Never as a group",
    why: ["Chesler Park, the Joint Trail, Druid Arch, and slickrock camps with 360° views; the best desert loop with real trails.", "Warm, dry, and the Thursday storms are the only weather all trip.", "No shuttle: a true loop."],
    whynot: ["Sites hold 7; eight of us means two sites on the same nights, which is the hard part in September.", "Water is nearly nonexistent; expect to cache or carry 4 L per person per day.", "Low mileage and gain; the challenge is heat and water, not terrain."],
    shape: "Thu 6 pm camp at Squaw Flat CG or BLM dispersed on the way in · Fri Elephant Hill → Chesler Park (CP sites), Joint Trail loop (7 mi) · Sat Elephant Canyon → Druid Arch → EC sites (7 mi) · Sun Lost Canyon → Peekaboo (LC sites) (7 mi) · Mon 4 mi out, drive home.",
    links: [["CleverHiker guide", "https://www.cleverhiker.com/backpacking/big-needles-loop-canyonlands-backpacking-guide/"], ["Chesler Park AllTrails", "https://www.alltrails.com/trail/us/utah/chesler-park"], ["Visit Utah", "https://www.visitutah.com/things-to-do/backpacking/canyon-country-southern-utah/big-needles-loop-canyonlands"]] },

  { id: "darkcanyon", region: "ut", name: "Dark Canyon: Woodenshoe → Dark → Peavine", where: "Dark Canyon Wilderness, Bears Ears NM, UT", th: "Woodenshoe TH, Elk Ridge (8,200 ft)",
    miles: 40, gain: 4000, high: 8200, nights: "3–4 on trail", drive: 6, driveNote: "via Blanding and the Elk Ridge dirt roads, 2 hr of dirt", fly: "SLC Tue",
    permits: "None (Manti-La Sal NF upper canyon)", bears: "Black bear in the upper forks; hang", wu: "ut/blanding",
    epic: 9, logistics: 4, novelty: 10, done: "Never",
    why: ["The wildest canyon on the board: from ponderosa on Elk Ridge to a 1,000-ft-deep desert gorge, ruins the whole way, nobody there.", "No permits, no crowds, warm nights.", "A genuine 'we did that' trip."],
    whynot: ["Forty miles is a five-day loop for most; four days means 10-mile days on faint trail with a 4-mi road walk at the end.", "Water is seasonal and scarce in the upper forks.", "Longest drive on the board and a rough approach for the Sprinter."],
    shape: "Thu 6 pm camp at Woodenshoe TH · Fri Woodenshoe Canyon to the Dark Canyon junction (11 mi) · Sat Dark Canyon to the Youngs Canyon area (10 mi) · Sun up Peavine Canyon (12 mi) · Mon 6 mi out plus the road walk, long drive home.",
    links: [["AllTrails loop", "https://www.alltrails.com/trail/us/utah/dark-canyon-loop--2"], ["Big Outside report", "https://thebigoutside.com/ancient-and-modern-folly-backpacking-utahs-dark-canyon/"], ["Visit Utah", "https://www.visitutah.com/things-to-do/backpacking/canyon-country-southern-utah/dark-canyon-wilderness"]] },
];

const SHORT = { spanish: "Spanish Peaks", cirque: "Cirque of the Towers", lizardhead: "Lizard Head Plateau", titcomb: "Titcomb Basin", teton: "Teton Crest",
  alice: "Alice–Toxaway", baron: "Baron Lakes traverse", whiteclouds: "White Clouds / Castle Peak", hyndman: "Hyndman Peak", kings: "Kings Peak", redcastle: "Red Castle",
  naturalist: "Naturalist Basin", tushar: "Tushar Skyline", grandgulch: "Grand Gulch", deathhollow: "Death Hollow", coyote: "Coyote Gulch", buckskin: "Buckskin Gulch",
  paria: "Paria Canyon", zion: "Zion Traverse", needles: "Needles loop", darkcanyon: "Dark Canyon" };
