/* Path Beaters '26 options board: route data.
   miles/gain/high are rounded from AllTrails or the linked guide; drive is hours from SLC airport and drivePoc hours from Pocatello (Dad's), highway estimates.
   epic / logistics / novelty are 1–10 gut ratings. wu is the Weather Underground town page (10-day forecast). */
const ROUTES = [
  { id: "spanish", region: "mt", name: "Spanish Peaks Loop", where: "Lee Metcalf Wilderness, Madison Range, MT", th: "Spanish Creek TH (6,100 ft)",
    miles: 20.5, gain: 4300, high: 9400, nights: "3 on trail", drive: 6.5, drivePoc: 4.75, driveNote: "via Pocatello; 4.5–5 hr from Dad's", fly: "BZN (1 hr) Monday",
    permits: "None", bears: "Grizzly: spray + canisters", wu: "mt/gallatin-gateway",
    epic: 7, logistics: 7, novelty: 10, done: "New range for us",
    why: ["Already planned, mapped, and waypointed; the rigs know the way.", "Big lake camps with room for eight, no permits, no shuttle.", "The Bozeman fly-out Monday is the cleanest exit of the bunch."],
    whynot: ["The wettest forecast on the board: storms likely Thursday night and all Friday, still showery Saturday.", "Longest drive from SLC.", "The one summit that fits (Blaze) is an off-trail scramble; no signature objective on trail."],
    shape: "Thu 6 pm rigs at TH or 3 mi in · Fri Spanish Lakes · Sat over the divide to Jerome Rock Lakes · Sun low camp on Falls Creek · Mon out by 10, BZN by 11:30.",
    sunOut: "from Jerome Rock Lakes down Falls Creek to the rigs, ~8 mi, −3,000 ft; BZN by evening",
    days: [["Thu", "rigs at the trailhead, or walk in to the creek camp", 3, 400, 0], ["Fri", "up to the Spanish Lakes (5 mi if we slept at the creek)", 5, 2600, 100], ["Sat", "over the divide, lunch at Lake Solitude, camp Jerome Rock Lakes", 4.5, 1100, 1000], ["Sun", "free morning, then down Falls Creek to the low camp", 3.5, 100, 1800], ["Mon", "past Pioneer Falls to the rigs, BZN by 11:30", 4.5, 100, 1300]],
    links: [["Trip site", "../"], ["AllTrails area", "https://www.alltrails.com/parks/us/montana/lee-metcalf-wilderness"]] },

  { id: "cirque", region: "wy", name: "Cirque of the Towers → Fremont Trail Loop", where: "Bridger Wilderness, Wind River Range, WY", th: "Big Sandy TH (9,100 ft)",
    miles: 25.5, gain: 4200, high: 11400, nights: "3 on trail", drive: 5, drivePoc: 5.5, driveNote: "last 40 mi is washboard dirt", fly: "SLC Mon night or Tue; JAC 2.5 hr",
    permits: "None (self-register)", bears: "Black bear country, grizzly possible; spray + storage", wu: "wy/boulder",
    epic: 10, logistics: 8, novelty: 6, done: "Winds in 2022 and 2024",
    why: ["The single most photographed backcountry skyline in the Lower 48, and Lonesome Lake camp sits right under it.", "A real loop with two passes; every day has a new basin.", "Texas Pass is a mild scramble that feels like an accomplishment without being dangerous when dry."],
    whynot: ["Thursday is stormy at Big Sandy; Friday is the iffy one at the high point, then it clears.", "Big Sandy is famous for a reason: expect neighbors at Lonesome Lake on a weekend.", "We've been to the Winds twice already; the novelty is in the Cirque itself, not the range."],
    shape: "Thu 6 pm camp at Big Sandy TH (big, free, vault toilet) · Fri Big Sandy Lake → Jackass Pass → Lonesome Lake (9 mi) · Sat Texas Pass → Shadow Lake / Washakie Creek (7 mi) · Sun Fremont Trail → Dads or Marms Lake (6 mi) · Mon 6 mi out, drive home.",
    sunOut: "Shadow Lake → Fremont Trail → Big Sandy, ~12 mi, mostly gentle",
    days: [["Thu", "camp at Big Sandy TH (big, free, vault toilet)", 0, 0, 0], ["Fri", "Big Sandy Lake, Jackass Pass, camp Lonesome Lake", 8.5, 2100, 900], ["Sat", "Texas Pass, camp Shadow Lake or Washakie Creek", 6.5, 1400, 1500], ["Sun", "Fremont Trail to Dads or Marms Lake", 4.5, 400, 700], ["Mon", "out to Big Sandy, drive home", 6, 300, 1000]],
    links: [["AllTrails", "https://www.alltrails.com/trail/us/wyoming/cirque-of-the-towers-to-fremont-trail-loop"], ["Bearfoot Theory guide", "https://bearfoottheory.com/cirque-of-the-towers-backpacking-wyoming/"], ["Girl on a Hike report", "https://girlonahike.com/hiking-the-cirque-of-the-towers-to-fremont-trail-loop.html"]] },

  { id: "titcomb", region: "wy", name: "Titcomb Basin from Island Lake (Pole Creek Trail)", where: "Bridger Wilderness, Wind River Range, WY", th: "Elkhart Park TH (9,300 ft)",
    miles: 30, gain: 4500, high: 10800, nights: "3 on trail", drive: 4.25, drivePoc: 4.25, driveNote: "paved to the trailhead, Pinedale is 15 mi away", fly: "SLC Mon night; JAC 1.5 hr",
    permits: "None", bears: "Grizzly range; spray + storage required", wu: "wy/pinedale",
    epic: 9, logistics: 8, novelty: 6, done: "Winds in 2022 and 2024",
    why: [], whynot: [],
    shape: "Thu camp at Elkhart Park · Fri 12 mi to Island Lake · Sat day-pack Titcomb Basin, camp Island Lake again · Sun 8 mi back to Seneca / Hobbs Lake · Mon 4 mi out.",
    sunOut: "Island Lake → Elkhart Park, ~12 mi",
    days: [["Thu", "camp at Elkhart Park (campground at the trailhead)", 0, 0, 0], ["Fri", "Pole Creek Trail past Seneca Lake to Island Lake", 12, 2500, 1500], ["Sat", "day pack into Titcomb Basin to the middle lake and back, camp Island Lake", 6, 500, 500], ["Sun", "back over Lester Pass side to Seneca or Hobbs Lake", 5, 800, 1100], ["Mon", "out to Elkhart Park", 7, 700, 1400]],
    links: [["AllTrails", "https://www.alltrails.com/trail/us/wyoming/titcomb-basin-via-pole-creek-trail-crooks-lakes-loop"], ["Hiking Walking guide", "https://www.hikingwalking.com/destinations/wy/wy_ww/elkhart_park/bp_islandlake/titcomb_basin"]] },




  { id: "alice", region: "id", name: "Alice–Toxaway Loop (Tin Cup Hiker)", where: "Sawtooth Wilderness, ID", th: "Tin Cup TH, Pettit Lake (7,000 ft)",
    miles: 24, gain: 4800, high: 9400, nights: "2–3 on trail", drive: 5, drivePoc: 3.75, driveNote: "via Twin Falls and Ketchum, paved to Pettit", fly: "SLC Mon night; BOI 3 hr",
    permits: "Free self-issue at TH", bears: "Black bear only; hang or canister", wu: "id/stanley",
    epic: 8, logistics: 9, novelty: 3, done: "Sawtooths 2017, 2020, 2021, 2023",
    why: ["Dries out fastest of anything north of Utah: sunny and near-zero precip by Saturday.", "The prettiest single lake-to-pass-to-lake day in Idaho, and we know the drive.", "Short enough to add the Imogene Lake extension (25 mi) if legs are fresh."],
    whynot: ["We've been to the Sawtooths four times; odds are somebody has done this exact loop.", "Only 19 miles and 3,000 ft: the lightest mountain challenge on the board.", "Pettit Lake is the busiest trailhead in the range on a nice September weekend."],
    shape: "Thu 6 pm camp at Pettit Lake CG · Fri 6 mi to Alice Lake · Sat over Snowyside Pass to Toxaway Lake (6 mi) · Sun Imogene Lake side trip, camp Farley/Edith · Mon 6 mi out, drive home.",
    sunOut: "Toxaway Lake → Farley Lake → Pettit Lake, ~7 mi",
    days: [["Thu", "camp at Pettit Lake CG", 0, 0, 0], ["Fri", "up to Alice Lake", 6, 1700, 100], ["Sat", "Snowyside Pass, camp Toxaway Lake", 4, 900, 1100], ["Sun", "Imogene Lake side trip, camp Farley or Edith Lake", 7, 2100, 1700], ["Mon", "out to Pettit Lake, drive home", 7, 100, 1800]],
    links: [["AllTrails", "https://www.alltrails.com/trail/us/idaho/tin-cup-hiker"], ["Imogene extension", "https://www.alltrails.com/trail/us/idaho/imogene-lake-to-toxaway-lake-to-alice-lake-loop"]] },





  { id: "chamberlain", region: "id", name: "Chamberlain Basin base camp under Castle Peak", where: "Cecil D. Andrus–White Clouds Wilderness, ID", th: "Fourth of July TH (8,800 ft)",
    miles: 22.5, gain: 4300, high: 9800, nights: "3 on trail", drive: 5.75, drivePoc: 4.25, driveNote: "Ketchum, over Galena, then 10 mi of decent dirt", fly: "SLC Mon night; BOI 3.5 hr",
    permits: "Free self-issue; group limit 12", bears: "Black bear only", wu: "id/stanley",
    epic: 9, logistics: 8, novelty: 10, done: "Never",
    why: [], whynot: [],
    shape: "Thu camp at Fourth of July TH · Fri over Chamberlain Divide to the basin · Sat day pack the lakes and Castle Lake · Sun back to Washington Lake · Mon out.",
    sunOut: "Chamberlain Basin → Fourth of July TH, ~10 mi",
    days: [["Thu", "camp at Fourth of July TH", 0, 0, 0], ["Fri", "Fourth of July Lake, Washington Lake, over Chamberlain Divide (9,800) to the basin", 8.5, 1900, 1500], ["Sat", "day pack: the three Chamberlain Lakes and Castle Lake under the north face", 5, 800, 800], ["Sun", "back over the divide, camp Washington Lake", 6, 1400, 1200], ["Mon", "out past Fourth of July Lake", 3, 200, 800]],
    links: [["AllTrails", "https://www.alltrails.com/trail/us/idaho/chamberlain-lake-trail-via-chamberlain-creek-trail-110"], ["Discover Sawtooth", "https://discoversawtooth.org/chamberlain-basin"], ["Mountains with Megan", "https://mountainswithmegan.com/chamberlain-basin-hike-stanley-idaho/"]] },

  { id: "boulderchain", region: "id", name: "Boulder Chain Lakes over Windy Devil (west side)", where: "Cecil D. Andrus–White Clouds Wilderness, ID", th: "Fourth of July TH (8,800 ft)",
    miles: 23, gain: 5000, high: 10400, nights: "3 on trail", drive: 5.75, drivePoc: 4.25, driveNote: "Ketchum, over Galena, then 10 mi of decent dirt", fly: "SLC Mon night; BOI 3.5 hr",
    permits: "Free self-issue; group limit 12", bears: "Black bear only", wu: "id/stanley",
    epic: 9, logistics: 8, novelty: 10, done: "Never",
    why: [], whynot: [],
    shape: "Thu camp at Fourth of July TH · Fri Born Lakes, Windy Devil, camp Hummock or Hourglass · Sat lakes day · Sun back over Windy Devil to Born Lakes · Mon out.",
    sunOut: "Hourglass Lake → Windy Devil → Fourth of July TH, ~9 mi",
    days: [["Thu", "camp at Fourth of July TH", 0, 0, 0], ["Fri", "Ants Basin, Born Lakes, over Windy Devil (10,300), camp Hummock or Hourglass Lake", 9.5, 2600, 1900], ["Sat", "short lakes day: Headwall and Lonesome Lakes, back to camp", 4, 400, 400], ["Sun", "back over Windy Devil, camp Born Lakes", 5, 1300, 1400], ["Mon", "out via Ants Basin", 4.5, 700, 1300]],
    links: [["AllTrails", "https://www.alltrails.com/trail/us/idaho/boulder-chain-lakes-trail"], ["Backcountry Post report", "https://backcountrypost.com/threads/idahos-white-cloud-mountains-boulder-chain-lakes-chamberlain-basin.8734/"]] },

  { id: "littleboulder", region: "id", name: "Boulder Chain Lakes up Little Boulder Creek (east side)", where: "Cecil D. Andrus–White Clouds Wilderness, ID", th: "Big Boulder Creek TH, Livingston Mill (7,100 ft)",
    miles: 27.5, gain: 5700, high: 10450, nights: "3 on trail", drive: 5.5, drivePoc: 3.5, driveNote: "Mackay, Challis, Clayton, then 10 mi of East Fork Salmon gravel", fly: "SLC Mon night",
    permits: "Free self-issue", bears: "Black bear only", wu: "id/mackay",
    epic: 9, logistics: 8, novelty: 10, done: "Never",
    why: [], whynot: [],
    shape: "Thu camp at Livingston Mill · Fri Little Boulder Creek to Willow Lake · Sat up the chain to Hummock Lake · Sun explore, drop to Willow Lake · Mon out.",
    sunOut: "Hummock Lake → Livingston Mill, ~12 mi",
    days: [["Thu", "camp at Livingston Mill", 0, 0, 0], ["Fri", "Little Boulder Creek over the divide to Frog Lake, camp Willow Lake", 9, 2600, 1100], ["Sat", "up the chain past Hatchet Lake, camp Hummock or Hourglass", 3.5, 900, 100], ["Sun", "Headwall and Lonesome Lakes, then back down to Willow Lake", 6, 1100, 1900], ["Mon", "out to Livingston Mill", 9, 1100, 2600]],
    links: [["AllTrails", "https://www.alltrails.com/trail/us/idaho/little-boulder-creek-trail-to-hummock-lake"], ["The Roam Wild guide", "https://theroamwild.com/boulder-chain-lakes/"]] },

  { id: "bornlakes", region: "id", name: "Born Lakes + Four Lakes Basin + Quiet Lake", where: "Cecil D. Andrus–White Clouds Wilderness, ID", th: "Fourth of July TH (8,800 ft)",
    miles: 18, gain: 4200, high: 10872, nights: "3 on trail", drive: 5.75, drivePoc: 4.25, driveNote: "Ketchum, over Galena, then 10 mi of decent dirt", fly: "SLC Mon night; BOI 3.5 hr",
    permits: "Free self-issue; group limit 12", bears: "Black bear only", wu: "id/stanley",
    epic: 9, logistics: 8, novelty: 10, done: "Never",
    why: [], whynot: [],
    shape: "Thu camp at Fourth of July TH · Fri Ants Basin to Born Lakes · Sat Four Lakes Basin, Quiet and Shallow Lakes · Sun Patterson Peak option, camp Born Lakes · Mon out.",
    sunOut: "Born Lakes → Fourth of July TH, ~5 mi",
    days: [["Thu", "camp at Fourth of July TH", 0, 0, 0], ["Fri", "Fourth of July Lake, Ants Basin, camp Born Lakes", 4.5, 1300, 700], ["Sat", "day pack to Four Lakes Basin and Quiet Lake, back to camp", 6, 1500, 1500], ["Sun", "Washington Lake loop or a rest day, camp Born Lakes", 3, 700, 700], ["Mon", "out via Ants Basin", 4.5, 700, 1300]],
    links: [["AllTrails Born Lakes", "https://www.alltrails.com/trail/us/idaho/fourth-of-july-creek-to-born-lakes"], ["AllTrails Four Lakes Basin", "https://www.alltrails.com/trail/us/idaho/four-lakes-basin-to-quiet-lake-scree-lake-and-shallow-lake"]] },

  { id: "champion", region: "id", name: "Champion Lakes under Washington Peak", where: "Cecil D. Andrus–White Clouds Wilderness, ID", th: "Champion Creek TH (7,400 ft, off Fourth of July Creek Rd)",
    miles: 23, gain: 4000, high: 9900, nights: "2\u20133 on trail", drive: 5.5, drivePoc: 4, driveNote: "Hwy 75 toward Clayton, then Champion Creek Rd dirt", fly: "SLC Mon night; BOI 3 hr",
    permits: "Free self-issue", bears: "Black bear only", wu: "id/stanley",
    epic: 9, logistics: 8, novelty: 10, done: "Never",
    why: [], whynot: [],
    shape: "Thu camp at Champion Creek TH · Fri up Champion Creek to the lower lake · Sat upper lakes and the Washington Peak shoulder · Sun fish and swim, or move to the lower lake · Mon out.",
    sunOut: "Champion Lakes → Champion Creek TH, ~8 mi",
    days: [["Thu", "camp at Champion Creek TH", 0, 0, 0], ["Fri", "Champion Creek Trail to the lower Champion Lake", 8, 1900, 600], ["Sat", "upper lakes and the Washington Peak shoulder, back to camp", 5, 1300, 1300], ["Sun", "fishing and swimming, or move down to the lower lake", 2, 200, 200], ["Mon", "out the way we came", 8, 600, 1900]],
    links: [["Backpacker: White Clouds", "https://www.backpacker.com/stories/hiking-idaho-s-white-cloud-mountains/"], ["AllTrails White Clouds lakes", "https://www.alltrails.com/parks/us/idaho/white-clouds-wilderness-area/lake"]] },

  { id: "kings", region: "utm", name: "Kings Peak via Henrys Fork", where: "High Uintas Wilderness, UT", th: "Henrys Fork TH (9,400 ft)",
    miles: 29.5, gain: 5100, high: 13528, nights: "2–3 on trail", drive: 2.75, drivePoc: 4.25, driveNote: "shortest of the big ones; 20 mi of good gravel at the end", fly: "SLC Mon evening, easy",
    permits: "None", bears: "Black bear; hang", wu: "wy/mountain-view",
    epic: 7, logistics: 10, novelty: 7, done: "Not as a group",
    why: ["Two-hour-forty-five drive means a real Thursday evening walk-in and a leisurely Monday.", "Summit day on the state high point, 13,528 ft, no technical ground.", "Dries out Saturday; a Sunday summit looks clean if the trend holds."],
    whynot: ["Thursday and Friday are the worst-looking forecast on the board: 83% storms Thursday, likely Friday, snow showers possible Saturday above 12,000 ft.", "Big open windy basins; camps are exposed and the Uintas lack the granite drama of the Winds.", "Henrys Fork is the busiest Uinta trailhead."],
    shape: "Thu 6 pm hike 3 mi to Alligator Lake · Fri to Dollar Lake (6 mi) · Sat Gunsight → Anderson Pass → Kings Peak → back (12 mi RT) · Sun down to Henrys Fork Lake or all the way out · Mon short walk out, home by lunch.",
    sunOut: "Dollar Lake → Henrys Fork TH, ~7 mi, gentle",
    days: [["Thu", "walk in to Alligator Lake", 3, 700, 100], ["Fri", "to Dollar Lake", 6, 1000, 200], ["Sat", "Gunsight Pass, Anderson Pass, Kings Peak, back to camp", 11, 3100, 3100], ["Sun", "down to the Henrys Fork Lake area", 5, 200, 900], ["Mon", "out, home by lunch", 4.5, 100, 800]],
    links: [["AllTrails", "https://www.alltrails.com/trail/us/utah/kings-peak-utah-highpoint-trail"], ["Highpoint guide", "https://highpoint.guide/ut/"]] },

  { id: "redcastle", region: "utm", name: "Red Castle Lakes (+ Smiths Fork Pass)", where: "High Uintas Wilderness, UT", th: "China Meadows TH (9,400 ft)",
    miles: 29, gain: 3300, high: 11800, nights: "2–3 on trail", drive: 2.75, drivePoc: 4.25, driveNote: "via Mountain View, WY; 20 mi of gravel", fly: "SLC Mon evening, easy",
    permits: "None", bears: "Black bear; hang", wu: "wy/mountain-view",
    epic: 8, logistics: 9, novelty: 8, done: "Never as a group",
    why: ["Red Castle is the most photogenic mountain in Utah and the lake under it is a 10 out of 10 camp.", "Short drive, gentle miles, and Smiths Fork Pass (11,800) as the challenge day with Kings Peak in view.", "Can link to Kings Peak for a 40-mi loop if the group wants more."],
    whynot: ["Same Thursday/Friday storm forecast as Kings.", "Out-and-back unless we do the long loop.", "Popular with Wyoming horse packers; expect stock at the lower lake."],
    shape: "Thu 6 pm hike 2 mi to the wilderness boundary meadows · Fri 9 mi to Lower Red Castle Lake, camp · Sat day pack: Upper Red Castle, Smiths Fork Pass, maybe the Wilson Peak ridge · Sun 7 mi back to Broadbent Meadow · Mon 4 mi out, home for dinner.",
    sunOut: "Lower Red Castle → China Meadows, ~11 mi, gentle",
    days: [["Thu", "walk in to the wilderness-boundary meadows", 2, 200, 0], ["Fri", "to Lower Red Castle Lake", 9, 1600, 300], ["Sat", "day pack: Upper Red Castle Lake and the Smiths Fork Pass overlook", 7, 1200, 1200], ["Sun", "down to Broadbent Meadow", 3, 100, 700], ["Mon", "out to China Meadows, home for dinner", 7, 200, 1000]],
    links: [["AllTrails (loop w/ Kings Peak)", "https://www.alltrails.com/trail/us/utah/red-castle-lake-and-king-s-peak-loop-from-china-meadows"]] },

  { id: "naturalist", region: "utm", name: "Naturalist + Four Lakes + Grandaddy Basins (Highline loop)", where: "High Uintas Wilderness, UT", th: "Highline TH, Hayden Pass (10,300 ft)",
    miles: 29.5, gain: 4600, high: 11300, nights: "3 on trail", drive: 2.25, drivePoc: 3.75, driveNote: "Mirror Lake Highway, paved to the trailhead", fly: "SLC Mon afternoon",
    permits: "None; Mirror Lake fee area for parking", bears: "Black bear; hang", wu: "ut/kamas",
    epic: 6, logistics: 10, novelty: 6, done: "Some of us in pieces",
    why: ["Closest trailhead on the board: dinner at the trailhead Thursday and still time to walk in.", "Three basins, dozens of lakes, Rocky Sea Pass; a lot of country for the miles.", "Bailout options everywhere if the weather turns."],
    whynot: ["The Uintas are rolling and forested; less 'epic' per mile than anything in Wyoming or Idaho.", "Thursday and Friday look wet here too.", "Weekend crowds from SLC on the near lakes."],
    shape: "Thu 6 pm hike 3 mi to Scudder Lake · Fri Naturalist Basin, Blue Lake, camp Jordan Lake (7 mi) · Sat Rocky Sea Pass → Four Lakes Basin (8 mi) · Sun Grandaddy Basin → Pinto Lake (8 mi) · Mon 5 mi out via the Highline.",
    sunOut: "Four Lakes Basin → Rocky Sea Pass → Highline TH, ~9 mi",
    days: [["Thu", "walk in to Scudder Lake", 2.5, 200, 300], ["Fri", "Naturalist Basin, Blue Lake, camp Jordan Lake", 6, 1200, 800], ["Sat", "Rocky Sea Pass to Four Lakes Basin", 8.5, 1900, 1700], ["Sun", "back over Rocky Sea Pass, camp Jordan Lake", 6.5, 900, 1100], ["Mon", "out via the Highline", 6, 400, 600]],
    links: [["AllTrails loop", "https://www.alltrails.com/trail/us/utah/highline-trailhead-loop-naturalist-four-lakes-and-grandaddy-basins"], ["Naturalist Basin guide", "https://girlonahike.com/backpacking-to-naturalist-basin-uintas.html"]] },

  { id: "tushar", region: "utm", name: "Tushar Skyline: Delano, Belknap, Baldy", where: "Tushar Mountains, Fishlake NF, UT", th: "Big John Flat TH (10,300 ft)",
    miles: 25, gain: 5100, high: 12169, nights: "2–3 on trail", drive: 3.75, drivePoc: 6.25, driveNote: "I-15 to Beaver, then 20 mi up UT-153 and forest road", fly: "SLC Mon evening, easy",
    permits: "None", bears: "Black bear; hang", wu: "ut/beaver",
    epic: 7, logistics: 9, novelty: 9, done: "Never; Utah's forgotten third range",
    why: ["Three 12,000-ft summits in a weekend from a tundra trail with mountain goats and no crowds.", "Drier than the Uintas Thursday and Friday.", "High trailhead, short drive, no permits."],
    whynot: ["Water is scarce on the Skyline; carry from the few springs.", "Not a lake-camp trip.", "Aspen gold is the show, and it peaks about a week later than our dates."],
    shape: "Thu 6 pm camp at Big John Flat · Fri Skyline Trail to Mud Lake / Blue Lake, tag Delano on the way (8 mi) · Sat Mount Belknap and Baldy from camp (8 mi RT) · Sun down to Bullion Pasture, camp (5 mi) · Mon 3 mi out, home by lunch.",
    sunOut: "Mud Lake → Big John Flat along the Skyline, ~8 mi",
    days: [["Thu", "camp at Big John Flat", 0, 0, 0], ["Fri", "Skyline Trail, tag Delano, camp Mud or Blue Lake", 9, 2200, 1500], ["Sat", "Mount Belknap and Baldy from camp", 8, 2200, 2200], ["Sun", "down to Bullion Pasture", 5, 500, 500], ["Mon", "out, home by lunch", 3, 200, 500]],
    links: [["Skyline Trail (Outdoor Project)", "https://www.outdoorproject.com/united-states/utah/tushar-skyline-trail-hike"], ["Delano Peak AllTrails", "https://www.alltrails.com/trail/us/utah/delano-peak"], ["Visit Utah three summits", "https://www.visitutah.com/articles/three-summits-tushar-mountains"]] },

  { id: "grandgulch", region: "ut", name: "Grand Gulch: Kane Gulch → Bullet Canyon", where: "Cedar Mesa, Bears Ears NM, UT", th: "Kane Gulch Ranger Station (6,500 ft)",
    miles: 23, gain: 1800, high: 6400, nights: "3 on trail", drive: 5.5, drivePoc: 7.75, driveNote: "via Moab, Blanding, UT-95, UT-261; paved to Kane Gulch", fly: "SLC Mon night or Tue",
    permits: "Required: BLM Cedar Mesa overnight permit, group cap 12, recreation.gov", bears: "None to speak of; mice and ravens", wu: "ut/blanding",
    epic: 8, logistics: 6, novelty: 10, done: "Never; a completely different kind of trip",
    why: ["Warm and drying: mid-70s days, low 50s nights, nearly clear from Saturday.", "Ruins, granaries, and panels around every bend; it's a walk through 900-year-old neighborhoods.", "Low mileage and gain leave energy for side canyons."],
    whynot: ["Permits are limited and must be reserved; a group of eight needs to land one now.", "Water is pools, sometimes brown, sometimes missing in September; carry capacity for a dry day.", "Not 'mountain epic': no passes, no summits, and the wash-bottom miles are sandy and slow."],
    shape: "Thu 6 pm camp at Kane Gulch (primitive) or Natural Bridges CG · Fri Kane Gulch → Junction Ruin → Todie area (7 mi) · Sat past Split Level and Sheiks Canyon to the Bullet junction (8 mi) · Sun up Bullet to Jailhouse and Perfect Kiva, camp near the rim (6 mi) · Mon 2 mi out; bike or second rig back to Kane Gulch.",
    sunOut: "Bullet junction → Bullet Canyon TH, ~7 mi, one steep step near the rim",
    days: [["Thu", "camp at Kane Gulch (or Natural Bridges CG)", 0, 0, 0], ["Fri", "Kane Gulch, Junction Ruin, camp near Todie", 7, 200, 1000], ["Sat", "past Split Level and Sheiks Canyon to the Bullet junction", 8.5, 400, 700], ["Sun", "up Bullet to Jailhouse and Perfect Kiva, camp near the rim", 5.5, 800, 200], ["Mon", "out; bike or second rig back to Kane Gulch", 2, 400, 100]],
    links: [["AllTrails", "https://www.alltrails.com/trail/us/utah/bullet-canyon-trail-to-grand-gulch-and-kane-gulch"], ["BLM Cedar Mesa permits", "https://www.blm.gov/visit/cedar-mesa"]] },

  { id: "deathhollow", region: "ut", name: "Death Hollow Loop (Boulder Mail Trail → Escalante River)", where: "Grand Staircase–Escalante NM, UT", th: "Boulder Mail Trail TH (6,600 ft)",
    miles: 21, gain: 1900, high: 6800, nights: "2–3 on trail", drive: 4.75, drivePoc: 6.75, driveNote: "via US-89 and Highway 12, one of the great drives", fly: "SLC Mon night, easy",
    permits: "Free self-issue at the TH; wag bags required in the canyons", bears: "None", wu: "ut/escalante",
    epic: 9, logistics: 8, novelty: 10, done: "Never; the wild card",
    why: ["Best forecast on the board: mid-70s, 20% precip or lower after Thursday, warm nights.", "Death Hollow is a legitimately hard canyon: wading, scrambling, route-finding, and the best swimming holes in Utah.", "Highway 12 in, free permits, and a short drive for the far-flung options."],
    whynot: ["Thursday storms in slot country mean flash-flood awareness; we don't drop into Death Hollow until Friday.", "Poison ivy is real and constant; long pants and no bare-armed bushwhacking.", "Only 22 mi; the challenge is the terrain, not the distance. Some of the crew may want a summit."],
    shape: "Thu 6 pm camp at the Boulder Mail Trail TH or Deer Creek CG · Fri Boulder Mail Trail across the slickrock, drop into Death Hollow (8 mi) · Sat down Death Hollow to the Escalante (7 mi, all wading) · Sun up the Escalante River toward town, camp in the corridor · Mon short walk out, 15-min shuttle between trailheads.",
    sunOut: "Escalante confluence → Escalante town TH along the river, ~7 mi of wading",
    days: [["Thu", "camp at the Boulder Mail Trail TH or Deer Creek CG", 0, 0, 0], ["Fri", "Boulder Mail Trail across the slickrock, drop into Death Hollow", 5.5, 900, 1800], ["Sat", "down Death Hollow to the Escalante, all wading", 8, 400, 900], ["Sun", "up the Escalante toward town, camp in the corridor", 5.5, 400, 200], ["Mon", "short walk out, 15-min shuttle", 2, 200, 100]],
    links: [["AllTrails", "https://www.alltrails.com/trail/us/utah/death-hollow-boulder-mail-trail-loop"], ["The Big Outside report", "https://thebigoutside.com/backpacking-utahs-mind-blowing-death-hollow-loop/"], ["Visit Utah guide", "https://www.visitutah.com/places-to-go/parks-outdoors/grand-staircase-escalante/hiking/boulder-mail-death-hollow"]] },

  { id: "coyote", region: "ut", name: "Coyote Gulch: Hurricane Wash → Crack-in-the-Wall", where: "Glen Canyon NRA / Escalante, UT", th: "Hurricane Wash TH, Hole-in-the-Rock Rd (4,600 ft)",
    miles: 16.5, gain: 1300, high: 4650, nights: "2–3 on trail", drive: 5, drivePoc: 8.5, driveNote: "Highway 12 then 35 mi of Hole-in-the-Rock washboard", fly: "SLC Mon night",
    permits: "Free self-issue at the TH", bears: "None", wu: "ut/escalante",
    epic: 8, logistics: 8, novelty: 9, done: "Never as a group",
    why: ["Jacob Hamblin Arch, Coyote Natural Bridge, and a creek you walk in under 400-ft walls: the desert postcard.", "Warm, dry, and easy walking; more time for exploring and less for suffering.", "Crack-in-the-Wall and the pack-hauling rope is a real bit of fun."],
    whynot: ["Popular: the arch camps fill on a September weekend.", "Easiest trip on the board; the challenge factor is low.", "Hole-in-the-Rock Road after Thursday rain can be a mess for the Sprinter."],
    shape: "Thu 6 pm camp at the trailhead (dispersed) · Fri Hurricane Wash into Coyote Gulch, camp near Jacob Hamblin Arch (8 mi) · Sat down-canyon past the bridge to the Escalante, camp lower gulch (6 mi) · Sun out Crack-in-the-Wall to the Fortymile Ridge TH (3 mi), shuttle, or stay a night at Dance Hall Rock · Mon drive home.",
    sunOut: "lower gulch → Crack-in-the-Wall → Fortymile Ridge TH, ~3 mi plus 600 ft of sand",
    days: [["Thu", "camp at the Hurricane Wash TH", 0, 0, 0], ["Fri", "Hurricane Wash into Coyote Gulch, camp near Jacob Hamblin Arch", 7.5, 100, 500], ["Sat", "past the natural bridge to the Escalante, camp lower gulch", 6, 200, 600], ["Sun", "Crack-in-the-Wall to Fortymile Ridge TH (600 ft of sand), or stay", 3, 1000, 100], ["Mon", "drive home", 0, 0, 0]],
    links: [["AllTrails loop", "https://www.alltrails.com/trail/us/utah/coyote-gulch-loop"], ["Bearfoot Theory guide", "https://bearfoottheory.com/coyote-gulch-backpacking-guide/"]] },

  { id: "buckskin", region: "ut", name: "Buckskin Gulch: Wire Pass → White House", where: "Paria Canyon–Vermilion Cliffs Wilderness, UT/AZ", th: "Wire Pass TH (4,900 ft) → White House TH",
    miles: 20, gain: 500, high: 4900, nights: "1–2 on trail", drive: 5.75, drivePoc: 8.25, driveNote: "US-89 past Kanab, 8 mi of House Rock Valley Rd dirt", fly: "SLC Mon night",
    permits: "Required: BLM, 20 people/night, reserve on recreation.gov; group max 10", bears: "None", wu: "ut/kanab",
    epic: 9, logistics: 4, novelty: 10, done: "Never",
    why: ["The longest slot canyon in the world: 13 miles of walls 400 ft high and 10 ft apart.", "Camp at the Buckskin–Paria confluence under 500-ft cliffs.", "Warm, and drying fast after Thursday."],
    whynot: ["Flash floods kill people here, and Thursday has storms in the forecast; we would not enter until the sky is clear.", "Overnight permits are capped and usually gone; check availability today.", "Too short for four days; pair with the Wave lottery or a Coyote Gulch day."],
    shape: "Thu 6 pm camp at Stateline CG near Wire Pass · Fri wait for a clear sky, Wire Pass → Buckskin → confluence camp (13 mi, wading) · Sat Paria narrows up to White House (7 mi), shuttle back, camp at White House · Sun Wave / Coyote Buttes lottery or Cottonwood Canyon Road side trip · Mon home.",
    sunOut: "already out Saturday; Sunday is the drive",
    days: [["Thu", "camp at Stateline CG near Wire Pass", 0, 0, 0], ["Fri", "clear sky only: Wire Pass, Buckskin, camp at the confluence", 13, 200, 900], ["Sat", "Paria narrows up to White House, shuttle, camp there", 7, 300, 100], ["Sun", "Wave lottery or Cottonwood Canyon Road side trip", 0, 0, 0], ["Mon", "home", 0, 0, 0]],
    links: [["AllTrails", "https://www.alltrails.com/trail/us/utah/wire-pass-trail-to-white-house-trailhead"], ["BLM permits", "https://www.blm.gov/programs/recreation/permits-and-passes/lotteries-and-permit-systems/arizona/paria-canyon"], ["Treeline Review guide", "https://www.treelinereview.com/where-to-go/buckskin-gulch-paria-canyon"]] },



  { id: "needles", region: "ut", name: "Big Needles Loop (Chesler Park, Druid Arch, Lost Canyon)", where: "Needles District, Canyonlands NP, UT", th: "Elephant Hill TH (5,300 ft)",
    miles: 25, gain: 2800, high: 5800, nights: "3 on trail", drive: 5.25, drivePoc: 8.0, driveNote: "via Moab and Monticello, paved to Elephant Hill", fly: "SLC Mon night",
    permits: "Required: NPS backcountry sites (max 7 per site), recreation.gov", bears: "None", wu: "ut/monticello",
    epic: 8, logistics: 5, novelty: 9, done: "Never as a group",
    why: ["Chesler Park, the Joint Trail, Druid Arch, and slickrock camps with 360° views; the best desert loop with real trails.", "Warm, dry, and the Thursday storms are the only weather all trip.", "No shuttle: a true loop."],
    whynot: ["Sites hold 7; eight of us means two sites on the same nights, which is the hard part in September.", "Water is nearly nonexistent; expect to cache or carry 4 L per person per day.", "Low mileage and gain; the challenge is heat and water, not terrain."],
    shape: "Thu 6 pm camp at Squaw Flat CG or BLM dispersed on the way in · Fri Elephant Hill → Chesler Park (CP sites), Joint Trail loop (7 mi) · Sat Elephant Canyon → Druid Arch → EC sites (7 mi) · Sun Lost Canyon → Peekaboo (LC sites) (7 mi) · Mon 4 mi out, drive home.",
    sunOut: "Druid Arch camp → Elephant Hill, ~6 mi",
    days: [["Thu", "camp at Squaw Flat CG or BLM dispersed", 0, 0, 0], ["Fri", "Elephant Hill to Chesler Park, Joint Trail loop", 7, 1000, 500], ["Sat", "Elephant Canyon and Druid Arch", 7, 700, 900], ["Sun", "Lost Canyon to Peekaboo", 7, 800, 900], ["Mon", "out to Elephant Hill, drive home", 4, 300, 500]],
    links: [["CleverHiker guide", "https://www.cleverhiker.com/backpacking/big-needles-loop-canyonlands-backpacking-guide/"], ["Chesler Park AllTrails", "https://www.alltrails.com/trail/us/utah/chesler-park"], ["Visit Utah", "https://www.visitutah.com/things-to-do/backpacking/canyon-country-southern-utah/big-needles-loop-canyonlands"]] },


  { id: "pioneers", region: "id", name: "Copper Basin: Goat, Betty, Baptie Lakes + Surprise Valley", where: "Pioneer Mountains, Salmon-Challis NF, ID", th: "Broad Canyon TH, Copper Basin (7,800 ft)",
    miles: 23.5, gain: 4700, high: 10600, nights: "3", drive: 5, drivePoc: 3, driveNote: "Mackay, then 25 mi of Copper Basin gravel; high clearance helps", fly: "SLC Sun night or Mon",
    permits: "None", bears: "Black bear only", wu: "id/mackay",
    epic: 9, logistics: 8, novelty: 10, done: "Never",
    why: [], whynot: [],
    shape: "Thu camp at Broad Canyon TH · Fri Broad Canyon → Betty Lake under Standhope Peak (6 mi) · Sat over the divide to Surprise Valley lakes (5 mi), camp · Sun Goat Lake and Baptie Lake side trip, camp Surprise Valley · Mon 6 mi out the Fall Creek side, rigs shuttled 15 min.",
    sunOut: "Betty Lake → Broad Canyon TH, ~6 mi",
    days: [["Thu", "camp at Broad Canyon TH", 0, 0, 0], ["Fri", "Broad Canyon to Betty Lake under Standhope Peak", 5.5, 2700, 100], ["Sat", "over the divide to the Surprise Valley lakes", 3.5, 400, 700], ["Sun", "Goat Lake and Baptie Lake side trip, camp Surprise Valley", 7, 1500, 1500], ["Mon", "out the Jarvis Trail to the rigs, 250 yards from where we started", 7.5, 100, 2900]],
    links: [["AllTrails", "https://www.alltrails.com/trail/us/idaho/goat-betty-and-baptie-lakes-via-broad-canyon-trail-061-and-jarvis-trail"], ["Girl on a Hike loop", "https://girlonahike.com/hiking-goat-betty-baptie-lakes-via-broad-canyon-loop.html"]] },

  { id: "bigboulder", region: "id", name: "Big Boulder Lakes via Walker Lake (east White Clouds)", where: "Cecil D. Andrus–White Clouds Wilderness, ID", th: "Big Boulder Creek TH, Livingston Mill (7,100 ft)",
    miles: 23.5, gain: 4600, high: 10800, nights: "2–3", drive: 5.5, drivePoc: 3.5, driveNote: "Mackay → Challis → Clayton, then 10 mi of East Fork Salmon gravel", fly: "SLC Sun night or Mon",
    permits: "Free self-issue", bears: "Black bear only", wu: "id/mackay",
    epic: 9, logistics: 8, novelty: 10, done: "Never",
    why: [], whynot: [],
    shape: "Thu camp at Livingston Mill · Fri Big Boulder Creek → Walker Lake (7 mi) · Sat off-trail to Cove, Sapphire, and Cirque Lakes, camp Cove Lake (3 mi) · Sun Hook Lake and the ridge under D.O. Lee Peak, camp again · Mon 10 mi out.",
    sunOut: "Walker Lake → Livingston Mill, ~7 mi",
    days: [["Thu", "camp at Livingston Mill", 0, 0, 0], ["Fri", "Big Boulder Creek to Walker Lake", 7, 2300, 200], ["Sat", "off-trail to Cove, Sapphire, and Cirque Lakes, camp Cove Lake", 3.5, 1000, 400], ["Sun", "Hook Lake and the ridge under D.O. Lee Peak, camp again", 4, 1100, 1100], ["Mon", "out to Livingston Mill", 9, 200, 2900]],
    links: [["AllTrails", "https://www.alltrails.com/trail/us/idaho/big-boulder-lakes-via-walker-lake"], ["Big Outside White Clouds", "https://thebigoutside.com/exploring-a-wilderness-hopeful-idahos-white-cloud-mountains/"]] },
];

const SHORT = { spanish: "Spanish Peaks", cirque: "Cirque of the Towers", titcomb: "Titcomb Basin",
  alice: "Alice–Toxaway", kings: "Kings Peak", redcastle: "Red Castle",
  naturalist: "Naturalist Basin", tushar: "Tushar Skyline", grandgulch: "Grand Gulch", deathhollow: "Death Hollow", coyote: "Coyote Gulch", buckskin: "Buckskin Gulch",
  needles: "Needles loop", pioneers: "Copper Basin Pioneers", bigboulder: "Big Boulder Lakes", chamberlain: "Chamberlain Basin", boulderchain: "Boulder Chain Lakes (west)", littleboulder: "Boulder Chain Lakes (east)", bornlakes: "Born Lakes + Four Lakes", champion: "Champion Lakes" };
